# Generated by Django 3.2.6 on 2021-08-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('forest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='api.forest')),
            ],
        ),
    ]
